# Generated by Django 2.1.2 on 2018-11-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('facial_encoding', models.TextField(blank=True, default='[]')),
                ('image', models.ImageField(default=None, upload_to='static/images/face')),
            ],
        ),
    ]
